// flow-typed signature: f3c4200e2f4e4e20a45de7dd6281fe8d
// flow-typed version: <<STUB>>/@turf/bezier_v^4.5.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/bezier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/bezier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/bezier/spline' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/bezier/index' {
  declare module.exports: $Exports<'@turf/bezier'>;
}
declare module '@turf/bezier/index.js' {
  declare module.exports: $Exports<'@turf/bezier'>;
}
declare module '@turf/bezier/spline.js' {
  declare module.exports: $Exports<'@turf/bezier/spline'>;
}
