// flow-typed signature: df53ac320d16f32eed1478b73f2ab64c
// flow-typed version: <<STUB>>/@turf/line-slice-along_v^4.5.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/line-slice-along'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/line-slice-along' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/line-slice-along/index' {
  declare module.exports: $Exports<'@turf/line-slice-along'>;
}
declare module '@turf/line-slice-along/index.js' {
  declare module.exports: $Exports<'@turf/line-slice-along'>;
}
