// flow-typed signature: 60529d10fe41943f8c61d7b49d7132f8
// flow-typed version: <<STUB>>/@turf/line-slice_v^4.4.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/line-slice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/line-slice' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/line-slice/index' {
  declare module.exports: $Exports<'@turf/line-slice'>;
}
declare module '@turf/line-slice/index.js' {
  declare module.exports: $Exports<'@turf/line-slice'>;
}
