// flow-typed signature: 310be539e452468f976778245a2ca9b6
// flow-typed version: <<STUB>>/@turf/meta_v^4.4.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/meta'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/meta' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/meta/index' {
  declare module.exports: $Exports<'@turf/meta'>;
}
declare module '@turf/meta/index.js' {
  declare module.exports: $Exports<'@turf/meta'>;
}
