// flow-typed signature: 26f66d8ed7625285bbff69b726edf7e6
// flow-typed version: <<STUB>>/freactal_v^1.1.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'freactal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'freactal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'freactal/lib/common' {
  declare module.exports: any;
}

declare module 'freactal/lib/context' {
  declare module.exports: any;
}

declare module 'freactal/lib/effects' {
  declare module.exports: any;
}

declare module 'freactal/lib/helpers' {
  declare module.exports: any;
}

declare module 'freactal/lib/index' {
  declare module.exports: any;
}

declare module 'freactal/lib/inject' {
  declare module.exports: any;
}

declare module 'freactal/lib/provide' {
  declare module.exports: any;
}

declare module 'freactal/lib/server/capture' {
  declare module.exports: any;
}

declare module 'freactal/lib/server/context' {
  declare module.exports: any;
}

declare module 'freactal/lib/server/index' {
  declare module.exports: any;
}

declare module 'freactal/lib/server/partial-render' {
  declare module.exports: any;
}

declare module 'freactal/lib/server/resolve-promise-tree' {
  declare module.exports: any;
}

declare module 'freactal/lib/server/set-state' {
  declare module.exports: any;
}

declare module 'freactal/lib/state' {
  declare module.exports: any;
}

// Filename aliases
declare module 'freactal/lib/common.js' {
  declare module.exports: $Exports<'freactal/lib/common'>;
}
declare module 'freactal/lib/context.js' {
  declare module.exports: $Exports<'freactal/lib/context'>;
}
declare module 'freactal/lib/effects.js' {
  declare module.exports: $Exports<'freactal/lib/effects'>;
}
declare module 'freactal/lib/helpers.js' {
  declare module.exports: $Exports<'freactal/lib/helpers'>;
}
declare module 'freactal/lib/index.js' {
  declare module.exports: $Exports<'freactal/lib/index'>;
}
declare module 'freactal/lib/inject.js' {
  declare module.exports: $Exports<'freactal/lib/inject'>;
}
declare module 'freactal/lib/provide.js' {
  declare module.exports: $Exports<'freactal/lib/provide'>;
}
declare module 'freactal/lib/server/capture.js' {
  declare module.exports: $Exports<'freactal/lib/server/capture'>;
}
declare module 'freactal/lib/server/context.js' {
  declare module.exports: $Exports<'freactal/lib/server/context'>;
}
declare module 'freactal/lib/server/index.js' {
  declare module.exports: $Exports<'freactal/lib/server/index'>;
}
declare module 'freactal/lib/server/partial-render.js' {
  declare module.exports: $Exports<'freactal/lib/server/partial-render'>;
}
declare module 'freactal/lib/server/resolve-promise-tree.js' {
  declare module.exports: $Exports<'freactal/lib/server/resolve-promise-tree'>;
}
declare module 'freactal/lib/server/set-state.js' {
  declare module.exports: $Exports<'freactal/lib/server/set-state'>;
}
declare module 'freactal/lib/state.js' {
  declare module.exports: $Exports<'freactal/lib/state'>;
}
