// flow-typed signature: bed586814f4bebbe9cc552b9e969f7f8
// flow-typed version: <<STUB>>/mailchimp-api-v3_v^1.7.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mailchimp-api-v3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mailchimp-api-v3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mailchimp-api-v3/examples/example' {
  declare module.exports: any;
}

declare module 'mailchimp-api-v3/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mailchimp-api-v3/examples/example.js' {
  declare module.exports: $Exports<'mailchimp-api-v3/examples/example'>;
}
declare module 'mailchimp-api-v3/index' {
  declare module.exports: $Exports<'mailchimp-api-v3'>;
}
declare module 'mailchimp-api-v3/index.js' {
  declare module.exports: $Exports<'mailchimp-api-v3'>;
}
declare module 'mailchimp-api-v3/test/basic.js' {
  declare module.exports: $Exports<'mailchimp-api-v3/test/basic'>;
}
