// flow-typed signature: 12277c3c504420fe8ce214cd82203107
// flow-typed version: <<STUB>>/prismic-dom_v^1.2.8/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prismic-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prismic-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prismic-dom/dist/prismic-dom' {
  declare module.exports: any;
}

declare module 'prismic-dom/dist/prismic-dom.min' {
  declare module.exports: any;
}

declare module 'prismic-dom/docs/assets/js/main' {
  declare module.exports: any;
}

declare module 'prismic-dom/docs/assets/js/search' {
  declare module.exports: any;
}

declare module 'prismic-dom/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prismic-dom/dist/prismic-dom.js' {
  declare module.exports: $Exports<'prismic-dom/dist/prismic-dom'>;
}
declare module 'prismic-dom/dist/prismic-dom.min.js' {
  declare module.exports: $Exports<'prismic-dom/dist/prismic-dom.min'>;
}
declare module 'prismic-dom/docs/assets/js/main.js' {
  declare module.exports: $Exports<'prismic-dom/docs/assets/js/main'>;
}
declare module 'prismic-dom/docs/assets/js/search.js' {
  declare module.exports: $Exports<'prismic-dom/docs/assets/js/search'>;
}
declare module 'prismic-dom/webpack.config.js' {
  declare module.exports: $Exports<'prismic-dom/webpack.config'>;
}
