// flow-typed signature: ddf2a78ace96f8154f0e8a0e8885d265
// flow-typed version: <<STUB>>/vitaminjs_vhttps://github.com/johangirod/vitaminjs#master/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vitaminjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vitaminjs' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vitaminjs/bin/vitamin.es5' {
    declare module.exports: any;
}

declare module 'vitaminjs/bin/vitamin' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/build/babelrc' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/build/resolveConfigLoader' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/build/webpack.config.client' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/build/webpack.config.common' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/build/webpack.config.server' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/build/webpack.config.tests' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/defaults' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/index' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/utils/defaultFunction' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/utils/emptyArray' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/utils/emptyObject' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/utils/hot' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/utils/index' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/utils/killProcess' {
    declare module.exports: any;
}

declare module 'vitaminjs/config/utils/transpile' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/chunks/modules/home' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/chunks/modules/module1' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/chunks/modules/module2' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/chunks/routes' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/counter/Counter/index' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/counter/reducers' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/counter/routes' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/actions/index' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/components/Explore' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/components/List' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/components/Repo' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/components/User' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/containers/App' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/containers/DevTools' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/containers/RepoPage' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/containers/UserPage' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/middleware/api' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/middleware/index' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/reducers/index' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/reducers/paginate' {
    declare module.exports: any;
}

declare module 'vitaminjs/examples/real-world-example/src/routes' {
    declare module.exports: any;
}

declare module 'vitaminjs/react-helmet' {
    declare module.exports: any;
}

declare module 'vitaminjs/react-redux' {
    declare module.exports: any;
}

declare module 'vitaminjs/react-resolver' {
    declare module.exports: any;
}

declare module 'vitaminjs/react-router-redux' {
    declare module.exports: any;
}

declare module 'vitaminjs/react-router' {
    declare module.exports: any;
}

declare module 'vitaminjs/redux' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/client/components/App' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/client/index' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/appMiddleware' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/components/App' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/components/DivLayout' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/components/ErrorPage/Error404' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/components/ErrorPage/Error500' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/components/ErrorPage/index' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/components/ErrorPage/Pineapple' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/components/HTMLLayout' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/middlewares/errorHandler' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/middlewares/initActionDispatcher' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/middlewares/renderer' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/middlewares/router' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/middlewares/staticAssetsServer' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/middlewares/store' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/render' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/server/server' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/shared/components/App' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/shared/components/CSSProvider' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/shared/defaultStateSerializer' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/shared/devTools' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/shared/index' {
    declare module.exports: any;
}

declare module 'vitaminjs/src/shared/store' {
    declare module.exports: any;
}

// Filename aliases
declare module 'vitaminjs/bin/vitamin.es5.js' {
    declare module.exports: $Exports<'vitaminjs/bin/vitamin.es5'>;
}
declare module 'vitaminjs/bin/vitamin.js' {
    declare module.exports: $Exports<'vitaminjs/bin/vitamin'>;
}
declare module 'vitaminjs/config/build/babelrc.js' {
    declare module.exports: $Exports<'vitaminjs/config/build/babelrc'>;
}
declare module 'vitaminjs/config/build/resolveConfigLoader.js' {
    declare module.exports: $Exports<'vitaminjs/config/build/resolveConfigLoader'>;
}
declare module 'vitaminjs/config/build/webpack.config.client.js' {
    declare module.exports: $Exports<'vitaminjs/config/build/webpack.config.client'>;
}
declare module 'vitaminjs/config/build/webpack.config.common.js' {
    declare module.exports: $Exports<'vitaminjs/config/build/webpack.config.common'>;
}
declare module 'vitaminjs/config/build/webpack.config.server.js' {
    declare module.exports: $Exports<'vitaminjs/config/build/webpack.config.server'>;
}
declare module 'vitaminjs/config/build/webpack.config.tests.js' {
    declare module.exports: $Exports<'vitaminjs/config/build/webpack.config.tests'>;
}
declare module 'vitaminjs/config/defaults.js' {
    declare module.exports: $Exports<'vitaminjs/config/defaults'>;
}
declare module 'vitaminjs/config/index.js' {
    declare module.exports: $Exports<'vitaminjs/config/index'>;
}
declare module 'vitaminjs/config/utils/defaultFunction.js' {
    declare module.exports: $Exports<'vitaminjs/config/utils/defaultFunction'>;
}
declare module 'vitaminjs/config/utils/emptyArray.js' {
    declare module.exports: $Exports<'vitaminjs/config/utils/emptyArray'>;
}
declare module 'vitaminjs/config/utils/emptyObject.js' {
    declare module.exports: $Exports<'vitaminjs/config/utils/emptyObject'>;
}
declare module 'vitaminjs/config/utils/hot.js' {
    declare module.exports: $Exports<'vitaminjs/config/utils/hot'>;
}
declare module 'vitaminjs/config/utils/index.js' {
    declare module.exports: $Exports<'vitaminjs/config/utils/index'>;
}
declare module 'vitaminjs/config/utils/killProcess.js' {
    declare module.exports: $Exports<'vitaminjs/config/utils/killProcess'>;
}
declare module 'vitaminjs/config/utils/transpile.js' {
    declare module.exports: $Exports<'vitaminjs/config/utils/transpile'>;
}
declare module 'vitaminjs/examples/chunks/modules/home.jsx' {
    declare module.exports: $Exports<'vitaminjs/examples/chunks/modules/home'>;
}
declare module 'vitaminjs/examples/chunks/modules/module1.jsx' {
    declare module.exports: $Exports<'vitaminjs/examples/chunks/modules/module1'>;
}
declare module 'vitaminjs/examples/chunks/modules/module2.jsx' {
    declare module.exports: $Exports<'vitaminjs/examples/chunks/modules/module2'>;
}
declare module 'vitaminjs/examples/chunks/routes.jsx' {
    declare module.exports: $Exports<'vitaminjs/examples/chunks/routes'>;
}
declare module 'vitaminjs/examples/counter/Counter/index.jsx' {
    declare module.exports: $Exports<'vitaminjs/examples/counter/Counter/index'>;
}
declare module 'vitaminjs/examples/counter/reducers.js' {
    declare module.exports: $Exports<'vitaminjs/examples/counter/reducers'>;
}
declare module 'vitaminjs/examples/counter/routes.jsx' {
    declare module.exports: $Exports<'vitaminjs/examples/counter/routes'>;
}
declare module 'vitaminjs/examples/real-world-example/src/actions/index.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/actions/index'>;
}
declare module 'vitaminjs/examples/real-world-example/src/components/Explore.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/components/Explore', >;
}
declare module 'vitaminjs/examples/real-world-example/src/components/List.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/components/List'>;
}
declare module 'vitaminjs/examples/real-world-example/src/components/Repo.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/components/Repo'>;
}
declare module 'vitaminjs/examples/real-world-example/src/components/User.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/components/User'>;
}
declare module 'vitaminjs/examples/real-world-example/src/containers/App.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/containers/App'>;
}
declare module 'vitaminjs/examples/real-world-example/src/containers/DevTools.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/containers/DevTools', >;
}
declare module 'vitaminjs/examples/real-world-example/src/containers/RepoPage.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/containers/RepoPage', >;
}
declare module 'vitaminjs/examples/real-world-example/src/containers/UserPage.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/containers/UserPage', >;
}
declare module 'vitaminjs/examples/real-world-example/src/middleware/api.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/middleware/api'>;
}
declare module 'vitaminjs/examples/real-world-example/src/middleware/index.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/middleware/index'>;
}
declare module 'vitaminjs/examples/real-world-example/src/reducers/index.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/reducers/index'>;
}
declare module 'vitaminjs/examples/real-world-example/src/reducers/paginate.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/reducers/paginate'>;
}
declare module 'vitaminjs/examples/real-world-example/src/routes.js' {
    declare module.exports: $Exports<'vitaminjs/examples/real-world-example/src/routes'>;
}
declare module 'vitaminjs/react-helmet.js' {
    declare module.exports: $Exports<'vitaminjs/react-helmet'>;
}
declare module 'vitaminjs/react-redux.js' {
    declare module.exports: $Exports<'vitaminjs/react-redux'>;
}
declare module 'vitaminjs/react-resolver.js' {
    declare module.exports: $Exports<'vitaminjs/react-resolver'>;
}
declare module 'vitaminjs/react-router-redux.js' {
    declare module.exports: $Exports<'vitaminjs/react-router-redux'>;
}
declare module 'vitaminjs/react-router.js' {
    declare module.exports: $Exports<'vitaminjs/react-router'>;
}
declare module 'vitaminjs/redux.js' {
    declare module.exports: $Exports<'vitaminjs/redux'>;
}
declare module 'vitaminjs/src/client/components/App.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/client/components/App'>;
}
declare module 'vitaminjs/src/client/index.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/client/index'>;
}
declare module 'vitaminjs/src/server/appMiddleware.js' {
    declare module.exports: $Exports<'vitaminjs/src/server/appMiddleware'>;
}
declare module 'vitaminjs/src/server/components/App.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/server/components/App'>;
}
declare module 'vitaminjs/src/server/components/DivLayout.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/server/components/DivLayout'>;
}
declare module 'vitaminjs/src/server/components/ErrorPage/Error404.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/server/components/ErrorPage/Error404'>;
}
declare module 'vitaminjs/src/server/components/ErrorPage/Error500.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/server/components/ErrorPage/Error500'>;
}
declare module 'vitaminjs/src/server/components/ErrorPage/index.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/server/components/ErrorPage/index'>;
}
declare module 'vitaminjs/src/server/components/ErrorPage/Pineapple.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/server/components/ErrorPage/Pineapple'>;
}
declare module 'vitaminjs/src/server/components/HTMLLayout.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/server/components/HTMLLayout'>;
}
declare module 'vitaminjs/src/server/middlewares/errorHandler.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/server/middlewares/errorHandler'>;
}
declare module 'vitaminjs/src/server/middlewares/initActionDispatcher.js' {
    declare module.exports: $Exports<'vitaminjs/src/server/middlewares/initActionDispatcher'>;
}
declare module 'vitaminjs/src/server/middlewares/renderer.js' {
    declare module.exports: $Exports<'vitaminjs/src/server/middlewares/renderer'>;
}
declare module 'vitaminjs/src/server/middlewares/router.js' {
    declare module.exports: $Exports<'vitaminjs/src/server/middlewares/router'>;
}
declare module 'vitaminjs/src/server/middlewares/staticAssetsServer.js' {
    declare module.exports: $Exports<'vitaminjs/src/server/middlewares/staticAssetsServer'>;
}
declare module 'vitaminjs/src/server/middlewares/store.js' {
    declare module.exports: $Exports<'vitaminjs/src/server/middlewares/store'>;
}
declare module 'vitaminjs/src/server/render.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/server/render'>;
}
declare module 'vitaminjs/src/server/server.js' {
    declare module.exports: $Exports<'vitaminjs/src/server/server'>;
}
declare module 'vitaminjs/src/shared/components/App.jsx' {
    declare module.exports: $Exports<'vitaminjs/src/shared/components/App'>;
}
declare module 'vitaminjs/src/shared/components/CSSProvider.js' {
    declare module.exports: $Exports<'vitaminjs/src/shared/components/CSSProvider'>;
}
declare module 'vitaminjs/src/shared/defaultStateSerializer.js' {
    declare module.exports: $Exports<'vitaminjs/src/shared/defaultStateSerializer'>;
}
declare module 'vitaminjs/src/shared/devTools.js' {
    declare module.exports: $Exports<'vitaminjs/src/shared/devTools'>;
}
declare module 'vitaminjs/src/shared/index.js' {
    declare module.exports: $Exports<'vitaminjs/src/shared/index'>;
}
declare module 'vitaminjs/src/shared/store.js' {
    declare module.exports: $Exports<'vitaminjs/src/shared/store'>;
}
